name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Use PAT instead of password

      - run: docker build -t rallycoding/multi-client ./client
      - run: docker build -t rallycoding/multi-nginx ./nginx
      - run: docker build -t rallycoding/multi-server ./server
      - run: docker build -t rallycoding/multi-worker ./worker

      - run: docker push rallycoding/multi-client
      - run: docker push rallycoding/multi-nginx
      - run: docker push rallycoding/multi-server
      - run: docker push rallycoding/multi-worker
