name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Use PAT instead of password

      - run: docker build -t haxon/multi-client ./client
      - run: docker build -t haxon/multi-nginx ./nginx
      - run: docker build -t haxon/multi-server ./server
      - run: docker build -t haxon/multi-worker ./worker

      - run: docker push haxon/multi-client
      - run: docker push haxon/multi-nginx
      - run: docker push haxon/multi-server
      - run: docker push haxon/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-654654509034
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

